### PR TITLE
Removed Alpha Documentation

### PR DESCRIPTION
**Pull request by pavankrish123**
Feature no longer supported.

### CODE REVIEW

**Comment by tehall16** [comment]
@pavankrish123 , did you want this PR merged?

**Comment by pavankrish123** [comment]
Yes please

**Comment by tehall16** [comment]
Merged

**Comment by tehall16** [comment]
Hey Pavan, it turns out that the page about containers is referenced in your documentation and breaks the pipeline when checking for dead links.  Can you remove the references to that?  Thanks!
image

**Pull request merged**
